// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "reviews": review Resource Client
//
// Command:
// $ goagen
// --design=github.com/annguyen1892/godesign/design
// --out=$(GOPATH)/src/reviews
// --version=v1.2.0-dirty

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// CreateReviewPath computes a request path to the create action of review.
func CreateReviewPath() string {

	return fmt.Sprintf("/reviews/")
}

// creates a review
func (c *Client) CreateReview(ctx context.Context, path string, payload *ProductReviewPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateReviewRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateReviewRequest create the request corresponding to the create action endpoint of the review resource.
func (c *Client) NewCreateReviewRequest(ctx context.Context, path string, payload *ProductReviewPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// ShowReviewPath computes a request path to the show action of review.
func ShowReviewPath(id int) string {
	param0 := strconv.Itoa(id)

	return fmt.Sprintf("/reviews/%s", param0)
}

// Get a review
func (c *Client) ShowReview(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowReviewRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowReviewRequest create the request corresponding to the show action endpoint of the review resource.
func (c *Client) NewShowReviewRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
