// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "reviews": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/annguyen1892/godesign/design
// --out=$(GOPATH)/src/reviews
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// ReviewHref returns the resource href.
func ReviewHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/reviews/%v", paramid)
}
